[[mainOverview]]
= Overview

Polar View Earth Observation Limited is working in collaboration with
EOX IT Services, Drift+Noise Polar Services, the Danish Meteorological
Institute, the Norwegian Meteorological Institute, and the Finnish
Meteorological Institute to develop a fully functional Use Case that
utilizes the DESP/DestinE system capabilities and data and adds value to
meet the needs of policy and decision makers who require information on
the past, current, and forecasted sea ice and other relevant conditions
for operational purposes in the Baltic Sea, European Arctic Ocean, and
the rest of the polar regions.

The Use Case will build on and complement existing operational and
climate sea ice products and services including those provided by the
Copernicus Marine Service, the national Ice Services, the ESA Polar
Thematic Exploitation Platform (Polar TEP), and the commercial
Drift+Noise IcySea app. The Use Case will augment and improve on the
current offerings by:

- Aggregating information of different types and from different
  sources to provide common products that span jurisdictional
  boundaries.

- Producing new products that will improve the ability of users to
  make good decisions.

- Making the products available in ways and means that are appropriate
  for the skills and requirements of different user communities.

One driver for the project is the regulation of the International
Maritime Organization (IMO) of the United Nations mandating that ships
operating in the polar regions meet certain requirements (the Polar
Code). Among other things, the Polar Code specifies a range of
information that ships traveling in polar waters are required to access
for planning and operations. The Use Case will demonstrate the value of
short and medium-term forecasts of sea ice, meteorological, and ocean
conditions suitable for strategic and tactical decision making by ships
and their owners.

A second driver for the project is the effect of climate change on polar
conditions that will impact long-term planning and policy development
for polar operations such as fishing, tourism, scientific research
campaigns, oil and gas development, and supplying northern communities.
The Use Case will deliver long-term forecasts of how changing sea ice
and other conditions will affect where different types of ships will be
able to travel in the polar regions compared to historical averages.

Benefits to polar operations and the rest of society will include
increased safety of life and property, decreased pollution, and
protection of sensitive environmental areas.
